name:                uploader
version:             0.1.0.0
github:              "githubuser/uploader"
license:             BSD3
author:              "Kamila Dzhavatova"
maintainer:          "kamila.dzhavatova@gmail.com"
copyright:           "2022 Kamila Dzhavatova"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/uploader#readme>

dependencies:
- base >= 4.7 && < 5
# Add time for timestamp generation
- time
# Add postgres for DDL/DML
- postgresql-simple >= 0.6.4
# Add random for random values in inserts
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  uploader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uploader
